services:
  postgres:
    image: postgres:15
    container_name: app_postgres
    environment:
      POSTGRES_USER: "simpleone"
      POSTGRES_PASSWORD: "qwerty"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  fetch_simpleone:
    build:
      context: .
    restart: unless-stopped  
    depends_on:
      - postgres
    extra_hosts:
      - "sd.irb.rest:83.217.25.60"
    env_file:
      - ./.prod.env
    command: sh -c "alembic upgrade head && python fetch_simpleone.py --groups 'config/our_groups.json' --req_params 'config/req_params.json'"
    volumes:
      - ./logs:/app/logs

  sla_checker:
    build:
      context: .
    restart: unless-stopped  
    depends_on:
      - postgres
    env_file:
      - ./.prod.env
    command: sh -c "alembic upgrade head && python sla_checker.py"
    volumes:
      - ./logs:/app/logs


volumes:
  postgres_data:
